# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9b770ce6-0d05-46cd-ae51-3f7e60e3ab6e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2FD1-DB61";
      fsType = "vfat";
    };

  fileSystems."/home/flomonster/mnt/shared" =
    { device = "/dev/disk/by-uuid/5AADCD15045156A2";
      fsType = "ntfs-3g";
      options = [ "nofail" "rw" "uid=1000"];
    };

  fileSystems."/home/flomonster/mnt/touro" =
    { device = "/dev/disk/by-uuid/61fed530-9829-4dd2-8b65-107ec163de9b";
      fsType = "ext4";
      options = [ "nofail" "rw" ];
    };

  fileSystems."/home/flomonster/mnt/cherry-box" =
    { device = "u482805@u482805.your-storagebox.de:/home";
      fsType = "sshfs";
      options = [ "nofail" "nodev" "noatime" "allow_other" "IdentityFile=/home/flomonster/.ssh/id_ed25519" "uid=1000" "gid=100" "default_permissions" "ssh_command=ssh -p 23"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/55b61408-ada5-4bbb-b381-47cd5640d803"; }
    ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
